### ISSUE TITLE
error generating images after upgrading from v0.6.0-pre to v0.6.1

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#116]
When upgrading from one of the v0.6.0 pre-release versions to the v0.6.1 release, the new face outscale slider may not be set correctly, leading to a type error when sending the image request:

```
TypeError: Cannot read properties of undefined (reading 'toFixed')
    at appendUpscaleToURL (main.js:39132:68)
    at Object.txt2img (main.js:39197:11)
    at Object.generateImage [as mutationFn] (main.js:65986:35)
    at Object.fn (main.js:37436:33)
    at run (main.js:36694:33)
    at new Retryer (main.js:36739:5)
    at Mutation2.executeMutation (main.js:37431:22)
    at main.js:37399:22
```

Since the state version changed between v0.5.0 and v0.6.0, that should erase existing/invalid state when upgrading from v0.5.0, and I think this is only an issue when coming from one of the v0.6.0 pre-release builds.

Clearing the app data should work, as usual.

**Comment by ssube** [comment]
I don't think this is happening when upgrading from v0.5.0 to v0.6.0, so I'm probably not going to add a migration unless that's also reported, but I have added a `Reset All` button to the client that will reset your local state. That will erase any prompts and parameters you have saved, but it should fix this error and similar ones.
