### ISSUE TITLE
error when using models that were converted at half precision

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#121]
I got an old Tesla card and wanted to try running SD v1.5 in half precision (float16) to see how much impact that had on iteration time and memory, but the app throws an error:

```
[2023-02-11 19:21:29,275] WARNING: onnx_web.device_pool: job txt2img_30355779_a564d65967cf739bc4ed10957d21b67b4e8abd388d8e3fa8ebc7827ae95b753a_1676143285.png failed with an error: ['Traceback (most recent call last):
', '  File "/home/ssube/onnx-web/api/onnx_web/device_pool.py", line 193, in job_done
    f.result()
', '  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
', '  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception\n', '  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
', '  File "/home/ssube/onnx-web/api/onnx_web/diffusion/run.py", line 54, in run_txt2img_pipeline
    result = pipe(
', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py", line 274, in __call__
    noise_pred = self.unet(sample=latent_model_input, timestep=timestep, encoder_hidden_states=prompt_embeds)
', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/diffusers/pipelines/onnx_utils.py", line 61, in __call__
    return self.model.run(None, inputs)
', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
', 'onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(float)) , expected: (tensor(float16))
']
```

The models convert correctly, but they don't run.

**Comment by ssube** [comment]
After patching `diffusers` to convert the latent input, `latent_model_input.astype(timestep_dtype)`, I'm encountering a second error:

```
[2023-02-12 16:22:49,050] WARNING: onnx_web.device_pool: job txt2img_1367455434_6fa46954b3c8cc947501a8fe46094588b8a7db729e8961ef6633c30b3296bec3_1676218944.png failed with an error: ['Traceback (most recent call last):
', '  File "/home/ssube/onnx-web/api/onnx_web/device_pool.py", line 209, in job_done
    f.result()
', '  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
', '  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
', '  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
', '  File "/home/ssube/onnx-web/api/onnx_web/diffusion/run.py", line 54, in run_txt2img_pipeline
    result = pipe(
', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py", line 296, in __call__
    [self.vae_decoder(latent_sample=latents[i : i + 1])[0] for i in range(latents.shape[0])]
', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py", line 296, in <listcomp>
    [self.vae_decoder(latent_sample=latents[i : i + 1])[0] for i in range(latents.shape[0])]
', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/diffusers/pipelines/onnx_utils.py", line 61, in __call__
    return self.model.run(None, inputs)
', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
', 'onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(float)) , expected: (tensor(float16))
']
```

**Comment by ssube** [comment]
I have this working, with two small patches to `stable_diffusion/pipeline_onnx_stable_diffusion.py` in `diffusers`:

```python
latent_model_input = latent_model_input.cpu().numpy().astype(timestep_dtype)
```

and

```python
image = np.concatenate(
    [self.vae_decoder(latent_sample=latents[i : i + 1].astype(timestep_dtype))[0] for i in range(latents.shape[0])]
)
```

I need to figure out if those are necessary or if I'm using the pipeline wrong, and potentially upstream them if they are needed.

Performance does not seem to be much faster, but running SD v1.5 using half precision takes about half as much VRAM:

![image](https://user-images.githubusercontent.com/451959/218323713-c2c34a83-0649-4c72-bfc5-151bf1b25e53.png)

**Comment by ssube** [comment]
Using `convert_float_to_float16` works in the sense that the model loads and renders an image, so long as `onnx.shape_inference.infer_shapes_path` has been called first, but it doesn't reduce memory usage nearly as much as a full FP16 model.

**Comment by ssube** [comment]
This has been fixed by patching the SD pipeline under certain environment/optimization combinations.

The full fp16 mode is currently hidden behind the `torch-fp16` optimization, and can be enabled during conversion and/or while running the server using `export ONNX_WEB_OPTIMIZATIONS=torch-fp16,others,...`. Because of the patch, models that have been converted at fp16 will be usable for inference when the optimization is not set, and vice versa, but that does incur some additional CPU copies.

The size on disk is about half that of an fp32 model and about 600MB less than an fp16 internally-optimized model:

```
4.0G    ./stable-diffusion-fp32
2.0G    ./stable-diffusion-fp16-torch
2.6G    ./stable-diffusion-fp16-inner
```

Memory usage is similarly reduced:

![Screenshot from 2023-03-19 10-40-11](https://user-images.githubusercontent.com/451959/226187769-2718bcb2-5585-4996-8c33-47b6b6d01278.png)
