### ISSUE TITLE
add a way to select a different VAE when converting diffusion models

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#145]
Many SD checkpoints need a different VAE, either from the original SD or a custom one. Provide an option in the extras file to load and include that.

**Comment by ssube** [comment]
This required a small change to the VAE conversion code:

```
[2023-02-17 01:05:11,258] INFO: onnx_web.convert.diffusion_original: converting VAE
[2023-02-17 01:05:11,264] ERROR: onnx_web.convert.diffusion_original: exception setting up output: ['Traceback (most recent call last):\n', '  File "/home/ssube/onnx-web/api/onnx_web/convert/diffusion_original.py", line 1316, in extract_checkpoint\n    converted_vae_checkpoint = convert_ldm_vae_checkpoint(vae_checkpoint, vae_config)\n', '  File "/home/ssube/onnx-web/api/onnx_web/convert/diffusion_original.py", line 646, in convert_ldm_vae_checkpoint\n    new_checkpoint = {"encoder.conv_in.weight": vae_state_dict["encoder.conv_in.weight"],\n', "KeyError: 'encoder.conv_in.weight'\n"]
[2023-02-17 01:05:11,264] ERROR: onnx_web.convert.diffusion_original: pipeline or config is not set, unable to continue.
[2023-02-17 01:05:11,410] INFO: onnx_web.convert.diffusion_original: converted original Diffusers checkpoint to Torch model
```
