### ISSUE TITLE
int64 vs int32 error using SD upscaling on Linux

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#147]
```
[2023-02-15 04:30:39,325] DEBUG: onnx_web.utils: running garbage collection
  0%|                                                                                                                                                                          | 0/25 [00:00<?, ?it/s]
[2023-02-15 04:30:39,416] WARNING: onnx_web.server.device_pool: job upscale_1543574075_07f7e7739c08ac67bd0aece4972c56e0390b9866bec3ee15d90ef2893cb83d57_1676435434.png failed with an error: ['Traceback (most recent call last):
', '  File "/home/ssube/onnx-web/api/onnx_web/server/device_pool.py", line 243, in job_done
    f.result()
', '  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
', '  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
', '  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
', '  File "/home/ssube/onnx-web/api/onnx_web/diffusion/run.py", line 226, in run_upscale_pipeline
    image = run_upscale_correction(
', '  File "/home/ssube/onnx-web/api/onnx_web/server/upscale.py", line 61, in run_upscale_correction
    return chain(
', '  File "/home/ssube/onnx-web/api/onnx_web/chain/base.py", line 138, in __call__
    image = process_tile_order(
', '  File "/home/ssube/onnx-web/api/onnx_web/chain/utils.py", line 106, in process_tile_order
    return process_tile_grid(source, tile, scale, filters, **kwargs)
', '  File "/home/ssube/onnx-web/api/onnx_web/chain/utils.py", line 39, in process_tile_grid
    tile_image = filter(tile_image, (left, top, tile))
', '  File "/home/ssube/onnx-web/api/onnx_web/chain/base.py", line 123, in stage_tile
    tile = stage_pipe(
', '  File "/home/ssube/onnx-web/api/onnx_web/chain/upscale_stable_diffusion.py", line 76, in upscale_stable_diffusion
    return pipeline(
', '  File "/home/ssube/onnx-web/api/onnx_web/diffusion/pipeline_onnx_stable_diffusion_upscale.py", line 157, in __call__
    noise_pred = self.unet(
', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/diffusers/pipelines/onnx_utils.py", line 61, in __call__
    return self.model.run(None, inputs)
', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
', 'onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int64)) , expected: (tensor(int32))
']
[2023-02-15 04:30:39,416] DEBUG: onnx_web.utils: running garbage collection
```

**Comment by ssube** [comment]
I never encountered this on Windows, likely because numpy on Windows uses an int32 by default and this was tested on my CUDA server: https://github.com/numpy/numpy/issues/9464
