### ISSUE TITLE
pipeline or config is not set error converting some models

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#164]
Trying to convert https://civitai.com/models/3666/protogen-x34-photorealism-official-release and https://civitai.com/models/3816/protogen-x53-photorealism-official-release both fail with an error:

```
[2023-02-17 05:28:18,709] ERROR: onnx_web.convert.diffusion_original: pipeline or config is not set, unable to continue.
[2023-02-17 05:28:18,841] INFO: onnx_web.convert.diffusion_original: converted original Diffusers checkpoint to Torch model
[2023-02-17 05:28:18,841] INFO: onnx_web.convert.diffusion_stable: converting Stable Diffusion model diffusion-protogen-x3-4: ../models/.cache/diffusion-protogen-x3-4-torch/working
 -> ../models/diffusion-protogen-x3-4/
```

Using

```json
  {
      "name": "diffusion-protogen-x3-4",
      "source": "civitai://4048?type=Pruned%20Model&format=SafeTensor",
      "format": "safetensors"
  },
  {
      "name": "diffusion-protogen-x5-3",
      "source": "civitai://4229?type=Pruned%20Model&format=SafeTensor",
      "format": "safetensors"
  },
```

**Comment by ssube** [comment]
For protogen 3.4:

```
[2023-03-17 13:56:09,949] ERROR: 3321037 140049413820416 onnx_web.convert.diffusion.original: exception setting up output: ['Traceback (most recent call last):\n', '  File "/opt/onnx-web/api/onnx_web/convert/diffusion/original
.py", line 1581, in extract_checkpoint\n    text_model = convert_ldm_clip_checkpoint(checkpoint)\n', '  File "/opt/onnx-web/api/onnx_web/convert/diffusion/original.py", line 970, in convert_ldm_clip_checkpoint\n    text_model.
load_state_dict(text_model_dict)\n', '  File "/opt/onnx-web/api/onnx_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict\n    raise RuntimeError(\'Error(s) in loading state_dict for {}:\
\n\\t{}\'.format(\n', 'RuntimeError: Error(s) in loading state_dict for CLIPTextModel:\n\tMissing key(s) in state_dict: "text_model.embeddings.position_ids", "text_model.embeddings.token_embedding.weight", "text_model.embeddin
gs.position_embedding.weight", "text_model.encoder.layers.0.self_attn.k_proj.weight", "text_model.encoder.layers.0.self_attn.k_proj.bias"
```

**Comment by ssube** [comment]
This appears to have been fixed when the `ONNX_WEB_CONVERT_EXTRACT` flag was updated to be false by default:

![image](https://github.com/ssube/onnx-web/assets/451959/1833dceb-cda2-4f7b-8352-ddf25a9e69cf)
