### ISSUE TITLE
torch JIT fails to load with various PKL file not found errors

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#167]
The tensor loading code tries safetensors, then `torch.jit`, then regular `torch.load`. The code path for safetensors does not fall back to `torch.load` if `torch.jit.load` fails, and it often does:

```
Message: 'failed to load as safetensors file, falling back to torch'
Arguments: (Exception('Error while deserializing header: HeaderTooLarge'),)
[2023-02-17 13:32:06,313] ERROR: onnx_web.convert.diffusion_original: exception setting up output: ['Traceback (most recent call last):\n', '  File "/home/ssube/onnx-web/api/onnx_web/convert/utils.py", line 212, in load_tensor\n    checkpoint = safetensors.torch.load_file(name, device="cpu")\n', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/safetensors/torch.py", line 98, in load_file\n    with safe_open(filename, framework="pt", device=device) as f:\n', 'Exception: Error while deserializing header: HeaderTooLarge\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/home/ssube/onnx-web/api/onnx_web/convert/diffusion_original.py", line 1198, in extract_checkpoint\n    checkpoint = load_tensor(checkpoint_file, map_location=map_location)\n', '  File "/home/ssube/onnx-web/api/onnx_web/convert/utils.py", line 217, in load_tensor\n    checkpoint = torch.jit.load(name)\n', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/torch/jit/_serialization.py", line 162, in load\n    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n', 'RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found\n']
[2023-02-17 13:32:06,313] ERROR: onnx_web.convert.diffusion_original: pipeline or config is not set, unable to continue.
[2023-02-17 13:32:06,313] INFO: onnx_web.convert.diffusion_original: converted original Diffusers checkpoint to Torch model
[2023-02-17 13:32:06,314] INFO: onnx_web.convert.diffusion_stable: converting Stable Diffusion model diffusion-snow-globe-v1: ../models/.cache/diffusion-snow-globe-v1-torch/working -> ../models/diffusion-snow-globe-v1/
```

This looks like it might be related to https://github.com/pytorch/pytorch/issues/47917. The filename in the model, `constants.pkl`, varies by source and model but appears to always be another pickle file.

**Comment by ssube** [comment]
Loading that particular model using `torch.load` does work, but it is missing some necessary keys in the UNet area:

```
[2023-02-17 13:44:47,705] INFO: onnx_web.convert.diffusion_original: Pred and size are epsilon and 512, using config: /home/ssube/onnx-web/models/configs/v1-training-default.yaml
[2023-02-17 13:44:47,705] INFO: onnx_web.convert.diffusion_original: v1 model loaded.
[2023-02-17 13:44:47,729] INFO: onnx_web.convert.diffusion_original: converting UNet
[2023-02-17 13:44:51,999] ERROR: onnx_web.convert.diffusion_original: exception setting up output: ['Traceback (most recent call last):\n', '  File "/home/ssube/onnx-web/api/onnx_web/convert/diffusion_original.py", line 1289, in extract_checkpoint\n    converted_unet_checkpoint, has_ema = convert_ldm_unet_checkpoint(\n', '  File "/home/ssube/onnx-web/api/onnx_web/convert/diffusion_original.py", line 496, in convert_ldm_unet_checkpoint\n    new_checkpoint = {"time_embedding.linear_1.weight": unet_state_dict["time_embed.0.weight"],\n', "KeyError: 'time_embed.0.weight'\n"]
[2023-02-17 13:44:51,999] ERROR: onnx_web.convert.diffusion_original: pipeline or config is not set, unable to continue.
[2023-02-17 13:44:52,314] INFO: onnx_web.convert.diffusion_original: converted original Diffusers checkpoint to Torch model
```

**Comment by ssube** [comment]
I've successfully converted this model using the latest main, which has a fallback path when the Torch JIT load fails: https://github.com/ssube/onnx-web/blob/main/api/onnx_web/convert/utils.py#L225

The missing keys were caused by that fallback not unwrapping the `state_dict`, which now occurs as well, and the model works great:

![image](https://user-images.githubusercontent.com/451959/219876856-2512f77a-48e0-48d4-847a-bf1d45d45539.png)
