### ISSUE TITLE
module not found pytorch_lightning while converting model

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#168]
Some models seem to depend on outside modules that may not be available:

```
  File "/home/ssube/onnx-web/api/onnx_web/convert/__main__.py", line 336, in main
    convert_models(ctx, args, data)                                                                                                                                                   
  File "/home/ssube/onnx-web/api/onnx_web/convert/__main__.py", line 220, in convert_models
    convert_diffusion_original(                                                                                                                                                       
  File "/home/ssube/onnx-web/api/onnx_web/convert/diffusion_original.py", line 1428, in convert_diffusion_original
    extract_checkpoint(ctx, torch_name, source, config_file=model.get("config"), vae_file=model.get("vae"))                                                                          
  File "/home/ssube/onnx-web/api/onnx_web/convert/diffusion_original.py", line 1306, in extract_checkpoint
    vae_checkpoint = load_tensor(vae_file, map_location=map_location)                                                                                                               
  File "/home/ssube/onnx-web/api/onnx_web/convert/utils.py", line 220, in load_tensor                                                                                               
    logger.warning(                                                                                                                                                                 
  Message: 'failed to load with Torch JIT, falling back to PyTorch'
Arguments: (RuntimeError('PytorchStreamReader failed locating file constants.pkl: file not found'),)                                                                                
[2023-02-17 14:32:20,614] ERROR: onnx_web.convert.diffusion_original: exception setting up output: ['Traceback (most recent call last):\n', '  File "/home/ssube/onnx-web/api/onnx_w
eb/convert/utils.py", line 212, in load_tensor\n    checkpoint = safetensors.torch.load_file(name, device="cpu")\n', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-
packages/safetensors/torch.py", line 98, in load_file\n    with safe_open(filename, framework="pt", device=device) as f:\n', 'Exception: Error while deserializing header: HeaderToo
Large\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/home/ssube/onnx-web/api/onnx_web/convert/ut
ils.py", line 218, in load_tensor\n    checkpoint = torch.jit.load(name)\n', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/torch/jit/_serialization.py", l
ine 162, in load\n    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)\n', 'RuntimeError: PytorchStreamReader failed locating file constants.pkl: file
 not found\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/home/ssube/onnx-web/api/onnx_web/conve
rt/diffusion_original.py", line 1306, in extract_checkpoint\n    vae_checkpoint = load_tensor(vae_file, map_location=map_location)\n', '  File "/home/ssube/onnx-web/api/onnx_web/co
nvert/utils.py", line 223, in load_tensor\n    checkpoint = torch.load(name, map_location=map_location)\n', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/
torch/serialization.py", line 789, in load\n    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)\n', '  File "/home/ssube/onnx-web/api/onnx_env/lib/pyt
hon3.10/site-packages/torch/serialization.py", line 1131, in _load\n    result = unpickler.load()\n', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/torch/
serialization.py", line 1124, in find_class\n    return super().find_class(mod_name, name)\n', "ModuleNotFoundError: No module named 'pytorch_lightning'\n"]
[2023-02-17 14:32:20,615] ERROR: onnx_web.convert.diffusion_original: pipeline or config is not set, unable to continue.
[2023-02-17 14:32:20,770] INFO: onnx_web.convert.diffusion_original: converted original Diffusers checkpoint to Torch model
[2023-02-17 14:32:20,770] INFO: onnx_web.convert.diffusion_stable: converting Stable Diffusion model diffusion-pastel-mix: ../models/.cache/diffusion-pastel-mix-torch/working -> ..
/models/diffusion-pastel-mix/
```

**Comment by ssube** [comment]
This is specific to certain models that were created using https://pypi.org/project/pytorch-lightning/ and serialized to PickleTensors, which can import libraries/run code. This is one of the reasons not to use PickleTensor models, if SafeTensors are available, but it also can be fixed with `pip3 install pytorch_lightning`.
