### ISSUE TITLE
karras ve scheduler throwing an error

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#189]
```
[2023-02-19 16:54:46,835] DEBUG: onnx_web.server.model_cache: cache limit set to 0, not caching model: diffusion                                                                    [2023-02-19 16:54:46,835] DEBUG: onnx_web.server.model_cache: cache limit set to 0, not caching model: scheduler                                                                    
[2023-02-19 16:54:48,207] WARNING: onnx_web.server.device_pool: job txt2img_0_0637df289c9741e6f297abd4f8dc2e33740c22e8c7e0f0fb93c8550e43486387_1676825683.png failed with an error: ['Traceback (most recent call last):
', '  File "/home/ssube/onnx-web/api/onnx_web/server/device_pool.py", line 242, in job_done
    f.result()
', '  File "/usr/lib/python3.10/c
oncurrent/futures/_base.py", line 451, in result
    return self.__get_result()
', '  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
', '  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
', '  File "/home/ssube/onnx-web/
api/onnx_web/diffusion/run.py", line 58, in run_txt2img_pipeline
    result = pipe(
', '  File "/home/ssube/onnx-web/api/onnx_env/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py", line 283, in __call__
    scheduler_output = self.scheduler.step(\n', "TypeError: KarrasVeScheduler.step() missing 1 required
 positional argument: 'sample_hat'
"]  
```

**Comment by ssube** [comment]
I could wrap this scheduler and provide additional values to the `step` method, but as of diffusers 0.24.0, the scheduler has been deprecated: https://github.com/huggingface/diffusers/blob/v0.24.0/src/diffusers/schedulers/deprecated/scheduling_karras_ve.py#L164

I'm not going to add new patches to support deprecated schedulers/pipelines unless they offer something that the replacement does not, but I don't think that is the case here.
