### ISSUE TITLE
conv2d invalid combination of arguments when running im2img

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#20]
On my Win10/AMD test machine, I get the following error while running the im2img pipeline:

```
[2023-01-07 20:37:22,695] ERROR in app: Exception on /img2img [POST]                                                                          
Traceback (most recent call last):                                                                                                            
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\flask\app.py", line 2525, in wsgi_app                      
    response = self.full_dispatch_request()                                                                                                   
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request         
    rv = self.handle_user_exception(e)                                                                                                        
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request         
    rv = self.dispatch_request()                                                                                                              
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\flask\app.py", line 1796, in dispatch_request              
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)                                                                  
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_web\serve.py", line 234, in img2img                                              
    image = pipe(                                                                                                                             
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_d
iffusion_img2img.py", line 355, in __call__                                                                                                   
    init_latents = self.vae_encoder(sample=image)[0]                                                                                          
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl      
    return forward_call(*input, **kwargs)                                                                                                     
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\diffusers\models\vae.py", line 628, in forward             
    posterior = self.encode(x).latent_dist                                                                                                    
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\diffusers\models\vae.py", line 566, in encode
    h = self.encoder(x)                                                                                                                       
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl      
    return forward_call(*input, **kwargs)                                                                                                     
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\diffusers\models\vae.py", line 130, in forward             
    sample = self.conv_in(sample)                                                                                                             
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl      
    return forward_call(*input, **kwargs)                                                                                                     
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\torch\nn\modules\conv.py", line 464, in forward
    return self._conv_forward(input, self.weight, self.bias)                                                                                  
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\torch\nn\modules\conv.py", line 460, in _conv_forward      
    return F.conv2d(input, weight, bias, self.stride,                                                                                         
TypeError: conv2d() received an invalid combination of arguments - got (numpy.ndarray, Parameter, Parameter, tuple, tuple, tuple, int), but ex
pected one of:                                                                                                                                
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)                
      didn't match because some of the arguments have invalid types: (numpy.ndarray, Parameter, Parameter, tuple, tuple, tuple, int)          
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (numpy.ndarray, Parameter, Parameter, tuple, tuple, tuple, int)  
```

The txt2img pipeline works perfectly on the same machine, with acceleration, so this is somehow related to a difference between them. The input image is a good suspect, since the first parameter is a `numpy.ndarray` and not a `Tensor`, but it looks like there is some code in diffusers and/or onnx to convert PIL images into Tensors, so that may not be the issue.

This happens using both the DmlExecutionProvider and CPUExecutionProvider, which makes me think it is related to Win10 rather than AMD.

**Comment by ssube** [comment]
I was able to resolve this without any code changes, by deleting the ONNX models from disk and re-exporting them from the HuggingFace CLI cache (did not have to download them again).

It seems like this might be a version-related difference in how ONNX models are exported, specifically what parameters are converted to Tensors or not. After many hours of digging through Github and source, https://github.com/pytorch/pytorch/issues/82068#issuecomment-1194670568 was the closest thing I could find.

The only indicator of this problem in the logs appears when `DIFFUSERS_VERBOSITY=debug` and references the `AutoencoderKL` model instead of `OnnxRuntimeModel`.

Broken:

```
Updating config from {'vae_encoder': ('diffusers', 'AutoencoderKL'), 'vae_decoder': ('diffusers', 'OnnxRuntimeModel'), 'text_encoder': ('diffusers', 'OnnxRuntimeModel'), 'tokenizer': ('transfo
rmers', 'CLIPTokenizer'), 'unet': ('diffusers', 'OnnxRuntimeModel'), 'scheduler': ('diffusers', 'EulerAncestralDiscreteScheduler'), 'safety_checker': (None, None), 'feature_extractor': ('trans
formers', 'CLIPImageProcessor')} to {'vae_encoder': ('diffusers', 'AutoencoderKL'), 'vae_decoder': ('diffusers', 'OnnxRuntimeModel'), 'text_encoder': ('diffusers', 'OnnxRuntimeModel'), 'tokeni
zer': ('transformers', 'CLIPTokenizer'), 'unet': ('diffusers', 'OnnxRuntimeModel'), 'scheduler': ('diffusers', 'EulerAncestralDiscreteScheduler'), 'safety_checker': (None, None), 'feature_extr
actor': ('transformers', 'CLIPImageProcessor'), 'requires_safety_checker': True}
```

Working:

```
Updating config from {'vae_encoder': ('diffusers', 'OnnxRuntimeModel'), 'vae_decoder': ('diffusers', 'OnnxRuntimeModel'), 'text_encoder': ('diffusers', 'OnnxRuntimeModel'), 'tokenizer': ('tran
sformers', 'CLIPTokenizer'), 'unet': ('diffusers', 'OnnxRuntimeModel'), 'scheduler': ('diffusers', 'PNDMScheduler'), 'safety_checker': ('diffusers', 'OnnxRuntimeModel'), 'feature_extractor': (
'transformers', 'CLIPImageProcessor')} to {'vae_encoder': ('diffusers', 'OnnxRuntimeModel'), 'vae_decoder': ('diffusers', 'OnnxRuntimeModel'), 'text_encoder': ('diffusers', 'OnnxRuntimeModel')
, 'tokenizer': ('transformers', 'CLIPTokenizer'), 'unet': ('diffusers', 'OnnxRuntimeModel'), 'scheduler': ('diffusers', 'PNDMScheduler'), 'safety_checker': ('diffusers', 'OnnxRuntimeModel'), '
feature_extractor': ('transformers', 'CLIPImageProcessor'), 'requires_safety_checker': True}
```

Setting the `vae_encoder` and `vae_decoder` params on the pipeline instance did not seem to help the broken model, but did not break the working model either. Setting the `tensor_format` and `revision` on the pipeline/scheduler made no difference. Eventually I just exported the model again.
