### ISSUE TITLE
error converting models with non-default models directory

### ISSUE THREAD

**Issue by bzlibby** [ssube/onnx-web#221]
After moving my models directory to a separate drive, I am unable to finish converting new models added to my extras file. My launch script has been updated to point to the correct directory, but something in the conversion process appears to be looking for the original directory, which was already deleted and replaced with a symlink to the new directory. Interestingly, textual inversion conversions were totally successful, despite using the same extras file. The other models that I had previously converted are all in the directory that I moved, but were converted when the directory was still in the api directory.

Error message:
```
[2023-03-06 21:36:28,398] INFO: MainProcess MainThread onnx_web.convert.diffusion.original: Pred and size are epsilon and 512, using config: C:\Users\bzlib\onnx-web\api\models\configs\v1-training-default.yaml
[2023-03-06 21:36:28,398] INFO: MainProcess MainThread onnx_web.convert.diffusion.original: v1 model loaded.
[2023-03-06 21:36:28,399] WARNING: MainProcess MainThread onnx_web.convert.diffusion.original: unable to select a config file: C:\Users\bzlib\onnx-web\api\models\configs\v1-training-default.yaml
[2023-03-06 21:36:28,404] INFO: MainProcess MainThread onnx_web.convert.diffusion.original: converted original Diffusers checkpoint to Torch model
[2023-03-06 21:36:28,404] INFO: MainProcess MainThread onnx_web.convert.diffusion.diffusers: converting Stable Diffusion model diffusion-dream-world-v2-4: D:\onnx-models\.cache\diffusion-dream-world-v2-4-torch\working -> D:\onnx-models\diffusion-dream-world-v2-4/
[2023-03-06 21:36:28,404] ERROR: MainProcess MainThread __main__: error converting diffusion model diffusion-dream-world-v2-4: ['Traceback (most recent call last):\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_web\\convert\\__main__.py", line 222, in convert_models\n    convert_diffusion_original(\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_env\\lib\\site-packages\\torch\\autograd\\grad_mode.py", line 27, in decorate_context\n    return func(*args, **kwargs)\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_web\\convert\\diffusion\\original.py", line 1696, in convert_diffusion_original\n    convert_diffusion_diffusers(ctx, model, working_name)\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_env\\lib\\site-packages\\torch\\autograd\\grad_mode.py", line 27, in decorate_context\n    return func(*args, **kwargs)\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_web\\convert\\diffusion\\diffusers.py", line 115, in convert_diffusion_diffusers\n    pipeline = StableDiffusionPipeline.from_pretrained(\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_env\\lib\\site-packages\\diffusers\\pipeline_utils.py", line 515, in from_pretrained\n    config_dict = cls.load_config(cached_folder)\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_env\\lib\\site-packages\\diffusers\\configuration_utils.py", line 320, in load_config\n    raise EnvironmentError(\n', 'OSError: Error no file named model_index.json found in directory D:\\onnx-models\\.cache\\diffusion-dream-world-v2-4-torch\\working.\n']
```

Launch script:
```
set ONNX_WEB_BLOCK_PLATFORMS=cpu
set ONNX_WEB_MODEL_PATH=D:\onnx-models\
set ONNX_WEB_EXTRA_MODELS=D:\onnx-models\extras-copy.json
set ONNX_WEB_OPTIMIZATIONS=diffusers-attention-slicing,onnx-low-memory

echo "Downloading and converting models to ONNX format..."
python -m onnx_web.convert --sources --diffusion --upscaling --correction --extras=%ONNX_WEB_EXTRA_MODELS% --token=%HF_TOKEN%

echo "Launching API server..."
flask --app="onnx_web.main:run" run --host=0.0.0.0
```

Expected behavior: models can still be converted with the models directory in a different location.
Actual behavior: models cannot be fully converted after moving the models directory to a different location.

**Comment by ssube** [comment]
I pushed a likely fix for this, please try it out when you have a chance.

**Comment by bzlibby** [comment]
yep, this is working as expected now! I was able to convert a pretty sizable model (~4gb) without issue.
