### ISSUE TITLE
error when enabling long prompt weighting

### ISSUE THREAD

**Issue by bzlibby** [ssube/onnx-web#224]
After my most recent pull from `main`, I'm no longer able to use long prompt weighting when generating images. Instead, I get an infinite loading spinner in the UI and the following error message in the logs:

```
[2023-03-08 17:32:28,775] ERROR: onnx-web worker: directml MainThread onnx_web.worker.worker: error while running job: ['Traceback (most recent call last):\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_env\\lib\\site-packages\\huggingface_hub\\utils\\_errors.py", line 239, in hf_raise_for_status\n    response.raise_for_status()\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_env\\lib\\site-packages\\requests\\models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\n', 'requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/huggingface/diffusers/main/examples/community/D:%5Connx-web%5Capi%5Connx_web%5Cdiffusion.py\n', '\nThe above exception was the direct cause of the following exception:\n\n', 'Traceback (most recent call last):\n', '  File "D:\\onnx-web\\api\\onnx_web\\worker\\worker.py", line 48, in worker_main\n    fn(context, *args, **kwargs)\n', '  File "D:\\onnx-web\\api\\onnx_web\\diffusers\\run.py", line 31, in run_txt2img_pipeline\n    pipe = load_pipeline(\n', '  File "D:\\onnx-web\\api\\onnx_web\\diffusers\\load.py", line 217, in load_pipeline\n    pipe = pipeline.from_pretrained(\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_env\\lib\\site-packages\\diffusers\\pipeline_utils.py", line 528, in from_pretrained\n    pipeline_class = get_class_from_dynamic_module(\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_env\\lib\\site-packages\\diffusers\\dynamic_modules_utils.py", line 445, in get_class_from_dynamic_module\n    final_module = get_cached_module_file(\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_env\\lib\\site-packages\\diffusers\\dynamic_modules_utils.py", line 285, in get_cached_module_file\n    resolved_module_file = cached_download(\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_env\\lib\\site-packages\\huggingface_hub\\utils\\_validators.py", line 124, in _inner_fn\n    return fn(*args, **kwargs)\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_env\\lib\\site-packages\\huggingface_hub\\file_download.py", line 627, in cached_download\n    hf_raise_for_status(r)\n', '  File "C:\\Users\\bzlib\\onnx-web\\api\\onnx_env\\lib\\site-packages\\huggingface_hub\\utils\\_errors.py", line 280, in hf_raise_for_status\n    raise HfHubHTTPError(str(e), response=response) from e\n', 'huggingface_hub.utils._errors.HfHubHTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/huggingface/diffusers/main/examples/community/D:%5Connx-web%5Capi%5Connx_web%5Cdiffusion.py\n']
```

Currently running this commit: https://github.com/ssube/onnx-web/commit/26f4b7e5b9f9fbe1d0dd2279817086027fa8eafa
OS is Windows 10

**Comment by ssube** [comment]
I recently moved a few files around and renamed that directory, looks like I missed a reference.

Please test the fix when you have a chance.

**Comment by bzlibby** [comment]
Fix looks good to me, Long Prompt Weighting is working for me again!
