### ISSUE TITLE
progress queue full error

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#276]
The progress worker can crash in some unknown circumstances, leaving the client without progress updates and eventually the progress queue fills up:

```
[2023-03-22 02:33:49,678] DEBUG: 628727 140027216101376 onnx_web.worker.context: setting progress for job txt2img_108674247_04e4e598370a57a9d52aa981bdecc8aafb2ec096550e3c2352e3e[52/1886]
53_1679452417_0.png to 25                                                                                                                                                                 
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                          | 25/35 [00:11<00:04,  2.11it/s]
[2023-03-22 02:33:49,678] ERROR: 628727 140027216101376 onnx_web.worker.worker: error while running job                                                                                   
Traceback (most recent call last):                                                           
  File "/opt/onnx-web/api/onnx_web/worker/worker.py", line 52, in worker_main                                                                                                             
    job.fn(context, *job.args, **job.kwargs)
  File "/opt/onnx-web/api/onnx_web/diffusers/run.py", line 67, in run_txt2img_pipeline
    result = pipe(
  File "/opt/onnx-web/api/onnx_env/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py", line 289, in __call__
    callback(i, t, latents)
  File "/opt/onnx-web/api/onnx_web/worker/context.py", line 72, in on_progress
    self.set_progress(step)
  File "/opt/onnx-web/api/onnx_web/worker/context.py", line 94, in set_progress
    self.progress.put(
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 90, in put
    raise Full
queue.Full
[2023-03-22 02:33:49,678] WARNING: 628727 140027216101376 onnx_web.worker.context: setting failure for job txt2img_108674247_04e4e598370a57a9d52aa981bdecc8aafb2ec096550e3c2352e3e76a7d332
953_1679452417_0.png
```

**Comment by ssube** [comment]
This is still happening occasionally despite the fix that I put in place, and the logs indicate that the progress worker is running:

```
[2023-03-25 13:55:19,804] DEBUG: 87122 140133886051904 onnx_web.worker.pool: job count for device cuda: 3                                                                                             
[2023-03-25 13:55:19,804] DEBUG: 87122 140133886051904 onnx_web.worker.pool: recycling worker pool                                                                                                    
[2023-03-25 13:55:19,804] DEBUG: 87122 140133886051904 onnx_web.worker.pool: worker 98297 for device cuda does not need to be recycled                                                                
[2023-03-25 13:55:19,804] INFO: 87122 140133886051904 onnx_web.worker.pool: logger worker is healthy                                                                                                  
[2023-03-25 13:55:19,804] INFO: 87122 140133886051904 onnx_web.worker.pool: progress worker is healthy                                                                                                
[2023-03-25 13:55:19,804] DEBUG: 87122 140133886051904 onnx_web.worker.pool: worker pool recycled  
```

The code only restarts the logger and progress workers if they are not running/healthy.

**Comment by ssube** [comment]
Shutting down the API once it's in that state causes a few different `queue.Full` and `Queue is closed` errors:

```
^C
[2023-03-25 16:14:06,284] INFO: 163381 140442775126016 onnx_web.worker.worker: worker got keyboard interrupt
[2023-03-25 16:14:06,284] WARNING: 163381 140442775126016 onnx_web.worker.context: setting failure for job txt2img_1877250887_203b60329a839ed550667fddab3756bee3a5fa32800f4131328ac5c2ad626b80_1679757
696_0.png                                                                                          
[2023-03-25 16:14:06,284] INFO: 158736 139917108535296 __main__: shutting down app
[2023-03-25 16:14:06,284] INFO: 158736 139917108535296 onnx_web.worker.pool: stopping worker pool
[2023-03-25 16:14:06,284] DEBUG: 158736 139917108535296 onnx_web.worker.pool: closing queues
[2023-03-25 16:14:06,284] DEBUG: 158736 139917108535296 onnx_web.worker.pool: stopping device workers
[2023-03-25 16:14:06,284] DEBUG: 158736 139917108535296 onnx_web.worker.pool: stopping worker 163381 for device cuda
[2023-03-25 16:14:06,284] ERROR: 163381 140442775126016 onnx_web.worker.context: error setting failure on job txt2img_1877250887_203b60329a839ed550667fddab3756bee3a5fa32800f4131328ac5c2ad626b80_1679
757696_0.png                                                                                       
Traceback (most recent call last):                                                                 
  File "/opt/onnx-web/api/onnx_web/worker/worker.py", line 43, in worker_main
    job = context.pending.get(timeout=1.0)                                                         
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 113, in get           
    if not self._poll(timeout):                                                                                                                                                                       
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 257, in poll                                                                                                                         
    return self._poll(timeout)                                                                     
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)                   
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/onnx-web/api/onnx_web/worker/context.py", line 125, in fail
    self.progress.put(
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 90, in put
    raise Full
queue.Full
[2023-03-25 16:14:06,518] ERROR: 158736 139910216410688 onnx_web.worker.pool: value error in progress worker
Traceback (most recent call last):
  File "/opt/onnx-web/api/onnx_web/worker/pool.py", line 459, in progress_main
    progress = queue.get(timeout=(pool.join_timeout / 2))
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 100, in get
    raise ValueError(f"Queue {self!r} is closed")
ValueError: Queue <multiprocessing.queues.Queue object at 0x7f3f65531060> is closed
[2023-03-25 16:14:07,144] DEBUG: 158736 139917108535296 onnx_web.worker.pool: stopping worker 139910224803392 for thread logger
[2023-03-25 16:14:07,144] DEBUG: 158736 139917108535296 onnx_web.worker.pool: stopping worker 139910216410688 for thread progress
[2023-03-25 16:14:07,145] DEBUG: 158736 139917108535296 onnx_web.worker.pool: worker pool stopped
```

That seems to confirm that the progress worker is still running and listening on the progress queue, so I'm not sure where it's getting stuck - there should be little to no locking along that code path.

**Comment by ssube** [comment]
```
[2023-03-26 13:48:00,955] TRACE: 298496 140382315790336 onnx_web.diffusers.load: UNet parameter types: float32, float16, float16                                                                                                       
[2023-03-26 13:48:00,956] TRACE: 298496 140382315790336 onnx_web.diffusers.load: converting UNet sample to timestep dtype                                                                                                              
[2023-03-26 13:48:01,011] TRACE: 292154 140484756371008 onnx_web.worker.pool: empty value in progress worker                                                                                                                           
[2023-03-26 13:48:01,327] DEBUG: 298496 140382315790336 onnx_web.worker.context: setting progress for job txt2img_1710381580_2f3af9d870b071da48b90d27e629cf11f384ef9b985732e53fd08cb0c108876b_1679838394_0.png to 23                    69%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                             | 24/35 [00:08<00:04,  2.69it/s]
[2023-03-26 13:48:01,327] TRACE: 298496 140382315790336 onnx_web.diffusers.load: UNet parameter types: float32, float16, float16                                                                                                       
[2023-03-26 13:48:01,328] TRACE: 298496 140382315790336 onnx_web.diffusers.load: converting UNet sample to timestep dtype                                                                                                              [2023-03-26 13:48:01,511] TRACE: 292154 140484756371008 onnx_web.worker.pool: empty value in progress worker
[2023-03-26 13:48:01,700] DEBUG: 298496 140382315790336 onnx_web.worker.context: setting progress for job txt2img_1710381580_2f3af9d870b071da48b90d27e629cf11f384ef9b985732e53fd08cb0c108876b_1679838394_0.png to 24                    71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                       | 25/35 [00:09<00:03,  2.69it/s]
[2023-03-26 13:48:01,700] TRACE: 298496 140382315790336 onnx_web.diffusers.load: UNet parameter types: float32, float16, float16                                                                                                       [2023-03-26 13:48:01,700] TRACE: 298496 140382315790336 onnx_web.diffusers.load: converting UNet sample to timestep dtype
[2023-03-26 13:48:02,012] TRACE: 292154 140484756371008 onnx_web.worker.pool: empty value in progress worker       
[2023-03-26 13:48:02,072] DEBUG: 298496 140382315790336 onnx_web.worker.context: setting progress for job txt2img_1710381580_2f3af9d870b071da48b90d27e629cf11f384ef9b985732e53fd08cb0c108876b_1679838394_0.png to 25
 71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                       | 25/35 [00:09<00:03,  2.58it/s]
[2023-03-26 13:48:02,073] ERROR: 298496 140382315790336 onnx_web.worker.worker: error while running job            
Traceback (most recent call last):                                                                                 
  File "/opt/onnx-web/api/onnx_web/worker/worker.py", line 52, in worker_main                                      
    job.fn(context, *job.args, **job.kwargs)                                                                       
  File "/opt/onnx-web/api/onnx_web/diffusers/run.py", line 67, in run_txt2img_pipeline
    result = pipe(
  File "/opt/onnx-web/api/onnx_env/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py", line 289, in __call__
    callback(i, t, latents)
  File "/opt/onnx-web/api/onnx_web/worker/context.py", line 72, in on_progress
    self.set_progress(step)
  File "/opt/onnx-web/api/onnx_web/worker/context.py", line 94, in set_progress
    self.progress.put(
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 90, in put
    raise Full
queue.Full
```

The progress worker is still running and watching its queue, which appears to be empty despite actually being full.

That queue is created once with the worker pool, so it's somewhat unlikely that the new worker is attached to a new queue.

**Comment by ssube** [comment]
This may be related to design decisions in the Queue implementation, and it looks like replacing the pending and progress queues for each new worker is the most reliable solution. The old queues can be cleaned up once they are empty, which should happen shortly after the worker shuts down.

- https://bugs.python.org/issue20527
- https://stackoverflow.com/questions/21349850/multiprocessing-queue-deadlocks-after-reader-process-death
- https://stackoverflow.com/questions/69574959/python-multiprocessing-queue-not-putting-through-all-the-values
