### ISSUE TITLE
add support for LyCORIS networks: LoCON and LoHA

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#312]
Add support for LoRAs from https://github.com/KohakuBlueleaf/LyCORIS, which are pretty similar to the kohya_ss/sd-scripts LoRAs and already mostly work. They load and seem to generally work, but the results are rough/grainy and there are some blending errors in the logs:

```
RuntimeError: mat1 and mat2 shapes cannot be multiplied (245760x3 and 128x640)                                                                                                                   
[2023-04-02 22:34:26,056] ERROR: 876587 140367547742016 onnx_web.convert.diffusion.lora: error blending weights for key up_blocks_3_resnets_0_conv1                                              
Traceback (most recent call last):                                                                                                                                                               
  File "/opt/onnx-web/api/onnx_web/convert/diffusion/lora.py", line 119, in blend_loras                                                                                                          
    up_weight.squeeze(3).squeeze(2)                                                                                                                                                              
RuntimeError: mat1 and mat2 shapes cannot be multiplied (368640x3 and 128x320)                                                                                                                   
[2023-04-02 22:34:26,062] ERROR: 876587 140367547742016 onnx_web.convert.diffusion.lora: error blending weights for key up_blocks_3_resnets_0_conv2                                              
Traceback (most recent call last):                                                                                                                                                               
  File "/opt/onnx-web/api/onnx_web/convert/diffusion/lora.py", line 119, in blend_loras                                                                                                          
    up_weight.squeeze(3).squeeze(2)                                                                                                                                                              
RuntimeError: mat1 and mat2 shapes cannot be multiplied (122880x3 and 128x320)                                                                                                                   
[2023-04-02 22:34:26,069] ERROR: 876587 140367547742016 onnx_web.convert.diffusion.lora: error blending weights for key up_blocks_3_resnets_1_conv1                                              
Traceback (most recent call last):                                                                                                                                                               
  File "/opt/onnx-web/api/onnx_web/convert/diffusion/lora.py", line 119, in blend_loras                                                                                                          
    up_weight.squeeze(3).squeeze(2)                                                                                                                                                              
RuntimeError: mat1 and mat2 shapes cannot be multiplied (245760x3 and 128x320)                                                                                                                   
[2023-04-02 22:34:26,075] ERROR: 876587 140367547742016 onnx_web.convert.diffusion.lora: error blending weights for key up_blocks_3_resnets_1_conv2                                              
Traceback (most recent call last):                                                                                                                                                               
  File "/opt/onnx-web/api/onnx_web/convert/diffusion/lora.py", line 119, in blend_loras                                                                                                          
    up_weight.squeeze(3).squeeze(2)                                                                                                                                                              
RuntimeError: mat1 and mat2 shapes cannot be multiplied (122880x3 and 128x320)                                                                                                                   
[2023-04-02 22:34:26,082] ERROR: 876587 140367547742016 onnx_web.convert.diffusion.lora: error blending weights for key up_blocks_3_resnets_2_conv1                                              
Traceback (most recent call last):                                                                                                                                                               
  File "/opt/onnx-web/api/onnx_web/convert/diffusion/lora.py", line 119, in blend_loras                                                                                                          
    up_weight.squeeze(3).squeeze(2)                                                                                                                                                              
RuntimeError: mat1 and mat2 shapes cannot be multiplied (245760x3 and 128x320)                                                                                                                   
[2023-04-02 22:34:26,088] ERROR: 876587 140367547742016 onnx_web.convert.diffusion.lora: error blending weights for key up_blocks_3_resnets_2_conv2                                              
Traceback (most recent call last):                                                                                                                                                               
  File "/opt/onnx-web/api/onnx_web/convert/diffusion/lora.py", line 119, in blend_loras                                                                                                          
    up_weight.squeeze(3).squeeze(2)                                                                                                                                                              
RuntimeError: mat1 and mat2 shapes cannot be multiplied (122880x3 and 128x320)  
```

I believe there are mid nodes in use here, which are not being included by the logic in `blend_loras`, but as long as they use the same `nn` modules, that should be a matter of including the mids in the math.

**Comment by ssube** [comment]
There are a few errors left on some of the LoHA networks, such as:

- `cannot reshape array of size 102400 into shape (320,320,3,3)`
- `down_blocks_0_resnets_1_conv2 mat1 and mat2 shapes cannot be multiplied (4x320 and 4x320)`

**Comment by ssube** [comment]
Many LyCORIS networks are working, except those using CP decomposition. That math is trickier: https://github.com/KohakuBlueleaf/LyCORIS/issues/48

**Comment by ssube** [comment]
I made a few changes that seem to have CP decomp LoCONs working (ONNX models match within 1e-08), but LoHA is not working yet:

```
[2023-04-10 03:55:57,642] TRACE: 56457 139624776066880 onnx_web.convert.diffusion.lora: blending weights for LoHA keys: lora_unet_down_blocks_0_downsamplers_0_conv.hada_w1_a, lora_unet_down_blocks_0_downsamplers_0_conv.hada_w1_b, lora_unet_down_blocks_0_downsamplers_0_conv.hada_w2_a, lora_unet_down_blocks_0_downsamplers_0_conv.hada_w2_b, lora_unet_down_blocks_0_downsamp
lers_0_conv.alpha                                                                                                                                                                         [2023-04-10 03:55:57,642] TRACE: 56457 139624776066880 onnx_web.convert.diffusion.lora: blending weights for LoHA node: (torch.Size([4, 320]) @ torch.Size([4, 320])) * (torch.Size([4, 32
0]) @ torch.Size([4, 320]))                                                                                                                                                               
[2023-04-10 03:55:57,652] ERROR: 56457 139624776066880 onnx_web.worker.worker: unrecognized error while running job
Traceback (most recent call last):
  File "/opt/onnx-web/api/onnx_web/worker/worker.py", line 60, in worker_main
    job.fn(context, *job.args, **job.kwargs)
  File "/opt/onnx-web/api/onnx_web/diffusers/run.py", line 51, in run_txt2img_pipeline
    pipe = load_pipeline(
  File "/opt/onnx-web/api/onnx_web/diffusers/load.py", line 261, in load_pipeline
    blended_unet = blend_loras(
  File "/opt/onnx-web/api/onnx_web/convert/diffusion/lora.py", line 115, in blend_loras
    weights = (w1a_weight @ w1b_weight) * (w2a_weight @ w2b_weight)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x320 and 4x320)
```

**Comment by ssube** [comment]
LoHA with CP decomp is partially working, but has not been implemented in the merge tool yet, so I can't use that to create a reference model: https://github.com/KohakuBlueleaf/LyCORIS/blob/2ce8af1fe9c80c4aa0395a21ec7defae50e37cc9/lycoris/utils.py#L456

**Comment by ssube** [comment]
This is tentatively fixed, except for one code path through Conv2D nodes that have a 3x3 kernel but do not have `lora_mid` weights.
