### ISSUE TITLE
Error with --half and onnx-low-memory

### ISSUE THREAD

**Issue by HoopyFreud** [ssube/onnx-web#382]
with server on --half and onnx-low-memory enabled, the onnx runtime produces a matrix multiplication error

This error appears to be caused specifically by the enable_mem_reuse optimization for onnx-runtime. This error only occurs when  onnxruntime-directml 1.15.0 is installed; error does not appear with  onnxruntime-directml 1.14.1 installed.

Error:

2023-06-14 19:51:43.6750125 [E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running MatMul node. Name:'/text_model/encoder/layers.1/self_attn/out_proj/MatMul' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2448)\onnxruntime_pybind11_state.pyd!00007FFED69FC715: (caller: 00007FFED69FD982) Exception(3) tid(2ad4) 80070057 The parameter is incorrect.

[2023-06-14 19:51:43,680] ERROR: onnx-web worker: directml MainThread onnx_web.worker.worker: unrecognized error while running job
Traceback (most recent call last):
  File "G:\StableDiffusion\onnx-web\api\onnx_web\worker\worker.py", line 60, in worker_main
    job.fn(worker, *job.args, **job.kwargs)
  File "G:\StableDiffusion\onnx-web\api\onnx_web\diffusers\run.py", line 268, in run_txt2img_pipeline
    prompt_embeds = encode_prompt(
  File "G:\StableDiffusion\onnx-web\api\onnx_web\diffusers\utils.py", line 355, in encode_prompt
    return [
  File "G:\StableDiffusion\onnx-web\api\onnx_web\diffusers\utils.py", line 356, in <listcomp>
    pipe._encode_prompt(
  File "G:\StableDiffusion\onnx-web\api\onnx_env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "G:\StableDiffusion\onnx-web\api\onnx_web\diffusers\utils.py", line 130, in expand_prompt
    text_result = self.text_encoder(input_ids=group.astype(np.int32))
  File "G:\StableDiffusion\onnx-web\api\onnx_env\lib\site-packages\diffusers\pipelines\onnx_utils.py", line 60, in __call__
    return self.model.run(None, inputs)
  File "G:\StableDiffusion\onnx-web\api\onnx_env\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running MatMul node. Name:'/text_model/encoder/layers.1/self_attn/out_proj/MatMul' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2448)\onnxruntime_pybind11_state.pyd!00007FFED69FC715: (caller: 00007FFED69FD982) Exception(3) tid(2ad4) 80070057 The parameter is incorrect.

**Comment by ssube** [comment]
This has been reported twice now in Discord, both times with a fresh install of the Python packages, most likely both using ORT 1.15.0.

For now, I've pinned the packages in the requirements file to what should be a working combination, based on what I've been using to build the Windows bundles. That specifies ORT 1.14.x for now, but I still plan on fixing this so we can upgrade.
