### ISSUE TITLE
ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by ghost** [ssube/onnx-web#416]
Another repo, another error...

After running `api/setup-amd.bat`:

"Downloading and converting models to ONNX format..."
Traceback (most recent call last):
  File "C:\Users\f1am3d\miniconda3\envs\Automatic1111_olive\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\f1am3d\miniconda3\envs\Automatic1111_olive\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_web\__init__.py", line 2, in <module>
    from .chain import (
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_web\chain\__init__.py", line 1, in <module>
    from .pipeline import ChainPipeline, PipelineStage, StageParams
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_web\chain\pipeline.py", line 9, in <module>
    from ..output import save_image
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_web\output.py", line 13, in <module>
    from onnx_web.convert.utils import resolve_tensor
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_web\convert\utils.py", line 8, in <module>
    import requests
ValueError: source code string cannot contain null bytes

**Comment by f1am3d** [comment]
> Once the python shell starts up, try to `import requests`. If that prints the same error, the package is the problem. If not, please let me know.

Yes, it prints the same error.

> If the error is the same, you can run `pip install --force-reinstall requests` in the same command prompt, and that should replace any broken files from before.

Didn't help. I installed everything from scratch again - result is the same. 

`python ./scripts/test-diffusers.py
Traceback (most recent call last):
  File "C:\Users\f1am3d\repos\onnx-web\api\scripts\test-diffusers.py", line 1, in <module>
    from diffusers import OnnxStableDiffusionPipeline
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_env\lib\site-packages\diffusers\__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_env\lib\site-packages\diffusers\configuration_utils.py", line 29, in <module>
    from huggingface_hub import create_repo, hf_hub_download
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_env\lib\site-packages\huggingface_hub\__init__.py", line 322, in __getattr__
    submod = importlib.import_module(submod_path)
  File "C:\Users\f1am3d\miniconda3\envs\Automatic1111_olive\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_env\lib\site-packages\huggingface_hub\hf_api.py", line 35, in <module>
    from huggingface_hub.utils import (
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_env\lib\site-packages\huggingface_hub\utils\__init__.py", line 44, in <module>
    from ._headers import build_hf_headers, get_token_to_send, LocalTokenNotFoundError
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_env\lib\site-packages\huggingface_hub\utils\_headers.py", line 20, in <module>
    from ._runtime import (
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_env\lib\site-packages\huggingface_hub\utils\_runtime.py", line 20, in <module>
    import packaging.version
ValueError: source code string cannot contain null bytes`

**Comment by ssube** [comment]
The second error looks like it's from a different package:

```
  File "C:\Users\f1am3d\repos\onnx-web\api\onnx_env\lib\site-packages\huggingface_hub\utils\_runtime.py", line 20, in <module>
    import packaging.version
```

with `packaging.version` instead of `requests`. It sounds like you might have some broken packages installed from something else. 

You _could_ reinstall each of them, however, I recently released the Windows bundle for v0.11 which wraps Python and all of the necessary libraries into a single EXE file, which might make things easier: https://github.com/ssube/onnx-web/releases/tag/v0.11.0
