### ISSUE TITLE
500 error when any model parameters are empty

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#72]
Clicking Generate when any of the model parameters are empty will result in a 500 error with one of a few different stacktraces:

```
2023-01-22T03:29:45.288108043Z 100.64.0.23 - - [22/Jan/2023 03:29:45] "POST /api/txt2img?cfg=6.00&steps=25&scheduler=euler-a&seed=-1&prompt=an+astronaut+eating+a+hamburger&negativePrompt=&model=&platform=&upscaling=&correction=&width=512&height=512 HTTP/1.1" 200 -
2023-01-22T03:29:45.290858823Z exception calling callback for <Future at 0x7f7d100202b0 state=finished raised OSError>
2023-01-22T03:29:45.290875962Z Traceback (most recent call last):
2023-01-22T03:29:45.290880723Z   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
2023-01-22T03:29:45.290885052Z     callback(self)
2023-01-22T03:29:45.290890383Z   File "/usr/local/lib/python3.8/dist-packages/flask_executor/executor.py", line 37, in propagate_exceptions_callback
2023-01-22T03:29:45.290895923Z     raise exc
2023-01-22T03:29:45.290901303Z   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
2023-01-22T03:29:45.290907063Z     result = self.fn(*self.args, **self.kwargs)
2023-01-22T03:29:45.290912332Z   File "/usr/local/lib/python3.8/dist-packages/flask_executor/executor.py", line 29, in wrapper
2023-01-22T03:29:45.290918552Z     return fn(*args, **kwargs)
2023-01-22T03:29:45.290924612Z   File "/usr/local/lib/python3.8/dist-packages/flask/ctx.py", line 182, in wrapper
2023-01-22T03:29:45.290930192Z     return ctx.app.ensure_sync(f)(*args, **kwargs)
2023-01-22T03:29:45.290933812Z   File "/onnx-web/api/onnx_web/pipeline.py", line 96, in run_txt2img_pipeline
2023-01-22T03:29:45.290937692Z     pipe = load_pipeline(OnnxStableDiffusionPipeline,
2023-01-22T03:29:45.290941232Z   File "/onnx-web/api/onnx_web/pipeline.py", line 62, in load_pipeline
2023-01-22T03:29:45.290944843Z     scheduler=scheduler.from_pretrained(model, subfolder='scheduler')
2023-01-22T03:29:45.290948432Z   File "/usr/local/lib/python3.8/dist-packages/diffusers/schedulers/scheduling_utils.py", line 118, in from_pretrained
2023-01-22T03:29:45.290952443Z     config, kwargs = cls.load_config(
2023-01-22T03:29:45.290955872Z   File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 320, in load_config
2023-01-22T03:29:45.290959683Z     raise EnvironmentError(
2023-01-22T03:29:45.290963132Z OSError: Error no file named scheduler_config.json found in directory /data/models/..
```

**Comment by ssube** [comment]
I've fixed some of the more obvious cases, but there is still one error when a category of models is empty:

```
request from 127.0.0.1: 2 rounds of EulerAncestralDiscreteScheduler using ../models/stable-diffusion-onnx-v1-5 on DmlExecutionProvider, 512x512, 6.0, 926664022 - an astronaut eating a hamburger
invalid selection: 
[2023-01-22 15:40:22,477] ERROR in app: Exception on /api/txt2img [POST]
Traceback (most recent call last):
  File "/home/ssube/code/github/ssube/onnx-web/api/onnx_env/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ssube/code/github/ssube/onnx-web/api/onnx_env/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ssube/code/github/ssube/onnx-web/api/onnx_env/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/ssube/code/github/ssube/onnx-web/api/onnx_env/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ssube/code/github/ssube/onnx-web/api/onnx_env/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ssube/code/github/ssube/onnx-web/api/onnx_web/serve.py", line 388, in txt2img
    upscale = upscale_from_request()
  File "/home/ssube/code/github/ssube/onnx-web/api/onnx_web/serve.py", line 195, in upscale_from_request
    correction = get_from_list(request.args, 'correction', correction_models)
  File "/home/ssube/code/github/ssube/onnx-web/api/onnx_web/utils.py", line 115, in get_from_list
    selected = args.get(key, values[0])
IndexError: list index out of range
127.0.0.1 - - [22/Jan/2023 15:40:22] "POST /api/txt2img?cfg=6.00&steps=2&scheduler=euler-a&seed=-1&prompt=an+astronaut+eating+a+hamburger&negativePrompt=&model=&platform=&upscaling=&correction=&width=512&height=512 HTTP/1.1" 500 -
```
