### ISSUE TITLE
500 error when fill color has never been changed

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#74]
```
10.2.2.16 - - [22/Jan/2023 09:34:16] "POST /api/inpaint?cfg=6.00&steps=25&scheduler=euler-a&seed=-1&prompt=an+ice+queen,+reflection,+refraction,+volumetric+lighting,+depth+of+focus,+bokeh&negativePrompt=&model=s
table-diffusion-onnx-v1-inpainting&platform=amd&upscaling=upscaling-real-esrgan-x2-plus&correction=correction-gfpgan-v1-3&filter=none&noise=histogram&strength=1.00&fillColor=&denoise=0.50&faces=false&scale=2&outscale=2
&faceStrength=0.50&left=256&right=256&top=512&bottom=0 HTTP/1.1" 200 -
gc: objects in each generation: 341 0 227436
gc: objects in permanent generation: 0
gc: done, 195 unreachable, 0 uncollectable, 0.0310s elapsed
applying mask filter and generating noise source
exception calling callback for <Future at 0x1f1804dfc10 state=finished raised ValueError>
Traceback (most recent call last):
  File "C:\Users\ssube\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 342, in _invoke_callbacks
    callback(self)
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\flask_executor\executor.py", line 37, in propagate_exceptions_callback
    raise exc
  File "C:\Users\ssube\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\flask_executor\executor.py", line 29, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\flask\ctx.py", line 182, in wrapper
    return ctx.app.ensure_sync(f)(*args, **kwargs)
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_web\pipeline.py", line 190, in run_inpaint_pipeline
    source_image, mask_image, noise_image, _full_dims = expand_image(
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_web\image.py", line 177, in expand_image
    full_source = Image.new('RGB', dims, fill)
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\PIL\Image.py", line 2923, in new
    color = ImageColor.getcolor(color, mode)
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\PIL\ImageColor.py", line 136, in getcolor
    color, alpha = getrgb(color), 255
  File "C:\Users\ssube\stabdiff\onnx-try-2\onnx-web\api\onnx_env\lib\site-packages\PIL\ImageColor.py", line 120, in getrgb
    raise ValueError(msg)
ValueError: unknown color specifier: ''
```

**Comment by ssube** [comment]
This was fixed with https://github.com/ssube/onnx-web/commit/876b54a7a87d6610a1ea0223c5e315e73d6aa2f1 for the example request.
