### ISSUE TITLE
upscaling with Real ESRGAN fails on CUDA platform

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#77]
When DirectML is not available, upscaling fails:

```
2023-01-22T22:25:53.909984287Z /usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py:54: UserWarning: Specified provider 'DmlExecutionProvider' is not in available provider names.Available providers: 'TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider'
2023-01-22T22:25:53.909990197Z   warnings.warn(
2023-01-22T22:25:53.909993827Z exception calling callback for <Future at 0x7fd32e57b100 state=finished raised TypeError>
2023-01-22T22:25:53.909997797Z Traceback (most recent call last):
2023-01-22T22:25:53.910001297Z   File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
2023-01-22T22:25:53.910005147Z     callback(self)
2023-01-22T22:25:53.910008527Z   File "/usr/local/lib/python3.8/dist-packages/flask_executor/executor.py", line 37, in propagate_exceptions_callback
2023-01-22T22:25:53.910012557Z     raise exc
2023-01-22T22:25:53.910015987Z   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
2023-01-22T22:25:53.910019987Z     result = self.fn(*self.args, **self.kwargs)
2023-01-22T22:25:53.910023517Z   File "/usr/local/lib/python3.8/dist-packages/flask_executor/executor.py", line 29, in wrapper
2023-01-22T22:25:53.910027937Z     return fn(*args, **kwargs)
2023-01-22T22:25:53.910031247Z   File "/usr/local/lib/python3.8/dist-packages/flask/ctx.py", line 182, in wrapper
2023-01-22T22:25:53.910034907Z     return ctx.app.ensure_sync(f)(*args, **kwargs)
2023-01-22T22:25:53.910038297Z   File "/onnx-web/api/onnx_web/pipeline.py", line 122, in run_txt2img_pipeline
2023-01-22T22:25:53.910041987Z     image = upscale_resrgan(ctx, upscale, image)
2023-01-22T22:25:53.910045397Z   File "/onnx-web/api/onnx_web/upscale.py", line 152, in upscale_resrgan
2023-01-22T22:25:53.910048987Z     upsampler = make_resrgan(ctx, params, tile=512)
2023-01-22T22:25:53.910052367Z   File "/onnx-web/api/onnx_web/upscale.py", line 135, in make_resrgan
2023-01-22T22:25:53.910068437Z     upsampler = RealESRGANer(
2023-01-22T22:25:53.910072207Z   File "/usr/local/lib/python3.8/dist-packages/realesrgan/utils.py", line 70, in __init__
2023-01-22T22:25:53.910075977Z     model.load_state_dict(loadnet[keyname], strict=True)
2023-01-22T22:25:53.910079407Z TypeError: load_state_dict() got an unexpected keyword argument 'strict'
```

The request's provider is not being passed to the upscaling pipeline's inference session.

**Comment by ssube** [comment]
This was not just a CUDA issue, it was caused by renaming a keyword argument in https://github.com/ssube/onnx-web/commit/9d0a15900b8e2f1fcbe9c48a949ad32cc99a1f65, and should be fixed with https://github.com/ssube/onnx-web/commit/9bff64c7c9e1cad7440e6484550ff3a4006974bf
